before_install:
    - npm install -g browserify
    - npm install -g uglify-js

language: elm
elm:
    - latest-0.19.1

script:
    - make env=prod

before_deploy: 
    - rm .gitignore

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
